import { getChatGPTUser } from '@/app/chatgpt-auth';
import { database } from '@/db/store';
import { initial, kinds, mergeItems, type Item } from '@/lib/data';
import { z } from 'zod';
export const dynamic='force-dynamic';
const shape=z.object({id:z.string().min(1).max(80).regex(/^[a-zA-Z0-9-]+$/),kind:z.enum(kinds),name:z.string().trim().min(1).max(150),detail:z.string().max(2000),category:z.string().max(100),status:z.string().max(50),due:z.string().refine(s=>s===''||(/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s)))),url:z.string().max(2000).refine(s=>{if(!s)return true;try{const u=new URL(s);return u.protocol==='https:'&&!u.username&&!u.password}catch{return false}},'הקישור חייב להתחיל ב־https://'),assignee:z.string().max(80)});
async function identity(){const user=await getChatGPTUser();return user?.userId??(process.env.NODE_ENV==='development'?'local-preview':null);}
function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}});}
export async function GET(){const uid=await identity();if(!uid)return json({error:'יש להתחבר כדי לטעון נתונים.'},401);try{const rows=await database().prepare('SELECT * FROM records WHERE user_id = ?').bind(uid).all<Item>();return json({items:mergeItems(rows.results)});}catch{return json({error:'לא הצלחנו לטעון את הרשומות. נסו שוב.'},503);}}
export async function POST(req:Request){const uid=await identity();if(!uid)return json({error:'יש להתחבר כדי לשמור.'},401);
 const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return json({error:'הבקשה אינה מורשית.'},403);
 try{const raw=await req.text();if(raw.length>12000)return json({error:'הרשומה ארוכה מדי.'},413);let body;try{body=JSON.parse(raw)}catch{return json({error:'הבקשה אינה תקינה.'},400)}
 const parsed=shape.safeParse(body);if(!parsed.success)return json({error:'יש לבדוק את השדות ואת כתובת הקישור (https).'},400);const x=parsed.data;const db=database();const existing=await db.prepare('SELECT kind FROM records WHERE user_id=? AND id=?').bind(uid,x.id).first<{kind:string}>();const seed=initial.find(s=>s.id===x.id);if((existing&&existing.kind!==x.kind)||(seed&&seed.kind!==x.kind))return json({error:'לא ניתן לשנות סוג רשומה.'},400);
 if(x.kind==='vehicles'&&x.assignee){const employee=await db.prepare("SELECT id FROM records WHERE user_id=? AND id=? AND kind='employees' AND deleted=0").bind(uid,x.assignee).first();if(!employee)return json({error:'העובד שנבחר אינו קיים.'},400);}
 const updated=new Date().toISOString();await db.prepare('INSERT INTO records (user_id,id,kind,name,detail,category,status,due,url,assignee,updated,deleted) VALUES (?,?,?,?,?,?,?,?,?,?,?,0) ON CONFLICT(user_id,id) DO UPDATE SET name=excluded.name,detail=excluded.detail,category=excluded.category,status=excluded.status,due=excluded.due,url=excluded.url,assignee=excluded.assignee,updated=excluded.updated,deleted=0').bind(uid,x.id,x.kind,x.name,x.detail,x.category,x.status,x.due,x.url,x.assignee,updated).run();return json({item:{...x,updated}});
 }catch(e){if(String(e).includes('UNIQUE'))return json({error:'לעובד כבר משויך רכב. שחררו את השיוך הקיים לפני בחירת רכב אחר.'},409);return json({error:'השמירה נכשלה. הנתונים בטופס נשמרו; נסו שוב.'},503);}}
export async function DELETE(req:Request){const uid=await identity();if(!uid)return json({error:'יש להתחבר כדי למחוק.'},401);const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return json({error:'הבקשה אינה מורשית.'},403);const id=new URL(req.url).searchParams.get('id');if(!id||id.length>80)return json({error:'רשומה לא תקינה.'},400);try{const db=database();const seed=initial.find(x=>x.id===id);const now=new Date().toISOString();const statements=[db.prepare("UPDATE records SET assignee='',updated=? WHERE user_id=? AND kind='vehicles' AND assignee=?").bind(now,uid,id),db.prepare('UPDATE records SET deleted=1,updated=? WHERE user_id=? AND id=?').bind(now,uid,id)];if(seed)statements.push(db.prepare('INSERT INTO records (user_id,id,kind,name,updated,deleted) VALUES (?,?,?,?,?,1) ON CONFLICT(user_id,id) DO UPDATE SET deleted=1,updated=excluded.updated').bind(uid,id,seed.kind,seed.name,now));await db.batch(statements);return json({ok:true});}catch{return json({error:'המחיקה נכשלה. נסו שוב.'},503);}}
